"""
test_pipeline
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
     import datetime
    
     from airflow import DAG
     from airflow.operators.empty import EmptyOperator
    
     my_dag = DAG(
         dag_id="my_dag_name",
         start_date=datetime.datetime(2021, 1, 1),
         schedule="@daily",
     )
     EmptyOperator(task_id="task", dag=my_dag)

@dag(
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-08-01", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
)
def test_pipeline():
    python_1 = python_1_func()

dag_obj = test_pipeline()
